### ISSUE TITLE
Extract API signatures from source

### ISSUE THREAD

**Issue by andrew-codes** [Quillio/stringy#2]
The docs look great! I noticed the signature of each package's function(s) is hard-coded in their respective README file. Is there any interest in pulling this information from the source code of the package itself?

If so, I would be willing to explore this.

**Comment by walkerrandolphsmith** [comment]
The docs are generated from the READMEs to allow for them to be accessed without an internet connection. Since the README and implementation will have to be kept in sync it would be good to call that out in CONTRIBUTING.md. Open to bounce ideas around.

**Comment by andrew-codes** [comment]
You could run the site locally when offline if you still need the docs. I'm unsure which is less ideal: keeping the API in docs in sync with the real API or potentially needing to run a local site for docs if you are offline. Keep in mind that if you have the readme (repo), the likelihood is you also can run the site.

However, with that said, I suppose if you ship the READMEs with the packages when you publish them, then the above case may not be true. Not sure.

**Comment by walkerrandolphsmith** [comment]
So I can imagine reading the implementation to generate the docs. However there is still a bit of metadata missing from the implementation needed to generate the docs. For instance a description of the function, the return type, parameter types. Perhaps that metadata could live in the same file as a code comment. Is that more ideal than a README.md? They do suffer the same problem.

**Comment by walkerrandolphsmith** [comment]
Similar to JSDoc tags...

**Comment by walkerrandolphsmith** [comment]
Moved to #8. Thanks @andrew-codes.
