### ISSUE TITLE
Lerna is required as a global dependency

### ISSUE THREAD

**Issue by andrew-codes** [Quillio/stringy#3]
Is there a reason to not include Lerna as a dev dependency?

**Comment by walkerrandolphsmith** [comment]
Not a good reason. `Gatsby` should be included as a dev dependency in the `docs` (sub) package.

**Comment by andrew-codes** [comment]
Ah ok, so this can turn into an issue of removing global deps on lerna and gatsby then?

**Comment by walkerrandolphsmith** [comment]
Yes I'll go ahead and pick this one up. Thanks!
